### PR TITLE
[Feature Request] Add Lock button if lightdm is installed

### PR DESCRIPTION
**Pull request by ToMe25**
This PR adds a lock button that executes `/usr/bin/dm-tool lock` and then exits the program if lightdm is installed.
It might be preferable to use `lxlock` instead because that is a part of lxde, not lightdm, however that isn't installed on Raspberry Pis by default, and when it is installed using `sudo apt-get install lxlock` it doesn't work immediately either.

Why add this?
Because many similar tools have a lock function, and I, and surely others, missed it a lot.
I missed it even more before I knew about `dm-tool lock`.

## Other Changes
 * Fix translation keys for all languages. I assume no one has notices because the english one doesn't change anything?
 * Gitignore some more automatically generated files. There are still un-ignored automatically generated files left.

## Questions
 * What are the numbers for the translations in the translation files? Changing them doesn't seem to do anything, it works either way. I tested this with a non english language.
 * Should all the remaining automatically generated files be added to the `.gitignore` file?
 * Should lightdm be added as an optional dependency?

### CODE REVIEW

**Comment by spl237** [comment]
Thanks for your work on this, and I hope it is useful to you, but I'm afraid I won't be merging it.
I really don't want to add a fourth button to the shutdown dialog; it starts to get very cluttered, and locking the screen really isn't a shutdown operation, so it isn't a good fit from a usability point of view.
Also, it is very likely that we will be moving in the near future from lightdm to gdm, which will render this change obsolete.
Apologies, but I hope you can understand my reasons for not accepting the PR.

**Comment by ToMe25** [comment]
@spl237 I understand not wanting to add more buttons, especially ones that aren't directly shutdown related.

Do you know a good place to add a lock button?
The start menu seem to be designed for a lock button in the logout helper, like it is in what I assume to be the default one.
I would like it to be directly above the shutdown button, but I don't think that's possible.

Also if I extracted only the translation key fixes to a new PR, would that have a chance if getting merged?

**Comment by spl237** [comment]
I believe there is (or at least used to be) an optional plugin for the lxpanel taskbar which could lock the screen with a button on the taskbar; you could look at that.

I've looked at the translation key fixes - many thanks for spotting that bug, btw, I'd missed it. On looking at the issue, the correct thing to do (which is easier than modifying all the translation files) is to modify the original strings in the UI file, which I have now done. Many thanks for flagging the issue!

**Comment by ToMe25** [comment]
Thank you for implementing the language fixes.
The only thing that is still weird about the language files is that the `en_GB.po` file contains some underscores in the translated strings, but this doesn't show up on screen so I don't think its an issue.

About that plugin, I couldn't find it.
I did manually add a menu entry before implementing this.
This isn't exactly the way I would have wanted, but its good enough.
Screenshot-2021-10-08 15-41-30-1
I would have liked it to be directly above the Logout button, but its fine like this.

Thanks for your help.

**Comment by spl237** [comment]
The underscores in the translations should not appear in the displayed words; they indicate the letters which will be underlined as shortcuts when the Alt key is held down. For this reason, it makes more sense for them to be specific to the language files than in the master strings.

**Comment by ToMe25** [comment]
I did not know they had that function, I just assumed they were placed in the wrong line in the english translation by mistake, since they don't appear in any other language file.

Thanks for letting me know.

**Pull request closed without merging**
